[package]
name = "intptr"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"

license = "MIT"
authors = ["Casper <CasualX@users.noreply.github.com>"]
description = "Explicitly sized, typed pointers to memory outside the current address space."
documentation = "https://docs.rs/intptr/"
repository = "https://github.com/CasualX/intptr"
readme = "readme.md"

keywords = ["pointer", "address", "process-memory", "typed-pointer", "no-std"]
categories = ["memory-management", "no-std"]

[package.metadata.docs.rs]
all-features = true

[dependencies.serde]
version = "1.0"
optional = true
default-features = false

[dependencies.dataview]
version = "1.0"
optional = true
default-features = false
