name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.optional }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
            args: --features=serde,dataview
            optional: false
          - rust: beta
            args: --features=serde,dataview
            optional: false
          - rust: nightly
            args: --features=serde,dataview,nightly
            optional: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          default: true

      - name: Quick check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: ${{ matrix.args }}
