name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.optional }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: 1.85.0
            args: --features=serde,dataview
            optional: false
          - rust: stable
            args: --features=serde,dataview
            optional: false
          - rust: beta
            args: --features=serde,dataview
            optional: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Test
        run: cargo test ${{ matrix.args }}
